# varialbles
set $mod Mod4

# workspaces
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# colors
set $bg #222222
set $fg #d8a657
set $ur #ea6962
set $uf #a89984

# system apps
set $terminal footclient
set $browser firefox-developer-edition --new-tab
set $incognito $browser --new-tab --private-window
set $filemanager pcmanfm
set $pdfreader zathura
set $blueman ~/.config/custom_scripts/launch_tui.sh bluetui
set $audio_settings pavucontrol
set $lockscreen swaylock -i ~/.config/walls/lock.png
set $backgrounds ~/.config/custom_scripts/launch_tui.sh lf "$HOME/Pictures/backgrounds"

# launcher
set $app_menu fuzzel
set $command_menu_executables fuzzel --list-executables-in-path
set $emoji_picker rofimoji --selector fuzzel --action clipboard

# custom scripts
set $active_windows ~/.config/custom_scripts/sway_window_switcher.sh
set $executables ~/.config/custom_scripts/executeScripts.sh
set $powermenu ~/.config/custom_scripts/power.sh
set $wlsunset ~/.config/custom_scripts/wlsunset.sh
set $musicplayer ~/.config/custom_scripts/launch_tui.sh cmus
set $chooseBackground ~/.config/custom_scripts/chooseBackgroundImage.sh
set $waybarThemeSwitcher ~/.config/custom_scripts/waybarThemeSwitcher.sh

# custom scripts : bookmarks
set $bookmarks ~/.config/custom_scripts/bookmarks.sh tab all
set $bookmarks_window ~/.config/custom_scripts/bookmarks.sh window all
set $bookmarks_private ~/.config/custom_scripts/bookmarks.sh private all

set $bookmarks_category ~/.config/custom_scripts/bookmarks.sh tab category
set $bookmarks_category_window ~/.config/custom_scripts/bookmarks.sh window category
set $bookmarks_category_private ~/.config/custom_scripts/bookmarks.sh private category

# custom scripts : nmcli
set $connect_network ~/.config/custom_scripts/nmcli_connect_network.sh
set $delete_network ~/.config/custom_scripts/nmcli_delete_network.sh

# screenshot
set $full_screenshot grim ~/Pictures/screenshots/$(date +'%Y-%m-%d_%H-%M-%S.png') && notify-send -e "Screenshot taken"
set $edit_screenshot grim - | satty --no-window-decoration --filename - --output-filename ~/Pictures/screenshots/$(date '+%Y-%m-%d_%H-%M-%S.png')
