require("grimmvim.core.keymaps")
require("grimmvim.core.lazy")
require("grimmvim.core.options")
require("grimmvim.core.auto_commands")
require("grimmvim.core.custom_functions")
require("grimmvim.core.custom_highlight")
